import Head from "next/head";
import React, { useEffect } from "react";
import UiConcept from "../../components/UiConcept/UiConcept";
import { useRouter } from "next/router";
import { FullWidthPage, HideHeaderLogo } from "../../store/actions/toggle";
import { useDispatch } from "react-redux";

const index = ({ data }) => {
  const router = useRouter();
  const dispatch = useDispatch();

  useEffect(() => {
    router.pathname && dispatch(HideHeaderLogo()) && dispatch(FullWidthPage())
  }, [])

  return (
    <>
      <Head>
        <title>Ui Concept</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UiConcept data={data} />
    </>
  );
};

export default index;


export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://metadata.color.museum/api/v1/image/`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
