import Head from "next/head";
import React from "react";
import Change from "../../components/Change/Change";
import styles from "../../styles/modules/choose/choose.module.css";

const Id = () => {
  // debugger
  return (
    <>
      <Head>
        <title>Change</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.wrapper}>
        <Change />
      </section>
    </>
  );
};

export default Id;

export async function setServerSideProps({ params }) {
  // Fetch data from external API
  const res = await fetch(
    `https://metadata.color.museum/api/v1/image/get-image/${params.id}`
  );
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
