import Head from "next/head";
import React, { useEffect } from "react";
import { useDispatch } from "react-redux";
import Gallery from "../../../components/gallery/index";
import { ReceivedData } from "../../../store/actions/data";

const index = ({ data }) => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(ReceivedData(data.documents));
  }, [data]);

  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Gallery data={data} />
    </>
  );
};

export default index;

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://metadata.color.museum/api/v1/image/`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
