import Head from "next/head";
import React from "react";
import Choose from "../components/Choose/Choose";
import Header from "../components/Choose/Header";
import styles from "../styles/modules/choose/choose.module.css";

const choose = () => {
  return (
    <>
      <Head>
        <title>Choose</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.wrapper}>
        <Header choose={true} />
        <Choose />
      </section>
    </>
  );
};

export default choose;
