import Head from "next/head";
import React from "react";
import Describe from "../components/Describe/Describe";
import Header from "../components/Choose/Header";
import styles from "../styles/modules/choose/choose.module.css";

const describe = () => {
  return (
    <>
      <Head>
        <title>Describe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.wrapper}>
        <Header describe={true} />
        <Describe />
      </section>
    </>
  );
};

export default describe;
