import Head from "next/head";
import React from "react";
import Issues from "../components/Issues/Issues";

const issues = () => {
  return (
    <>
      <Head>
        <title>Issues</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Issues />
    </>
  );
};

export default issues;
