import Head from "next/head";
import React from "react";
import Header from "../components/Choose/Header";
import Success from "../components/Mint/Success";
import styles from "../styles/modules/choose/choose.module.css";

const mint_success = () => {
  return (
    <>
      <Head>
        <title>Mint Success</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.wrapper}>
        <Header mint={true} />
        <Success />
      </section>
    </>
  );
};

export default mint_success;
