import Head from "next/head";
import Header from "../components/Choose/Header";
import styles from "../styles/modules/choose/choose.module.css";
import Fail from "../components/Mint/Fail";

const mint_fail = () => {
  return (
    <>
      <Head>
        <title>Mint Fail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.wrapper}>
        <Header mint={true} />
        <Fail />
      </section>
    </>
  );
};

export default mint_fail;
