import styles from "../styles/modules/choose/choose.module.css";
import Head from "next/head";
import Header from "../components/Choose/Header";
import Pending from "../components/Mint/Pending";

const mint_pending = () => {
  return (
    <>
      <Head>
        <title>Mint Pending</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.wrapper}>
        <Header mint={true} />
        <Pending />
      </section>
    </>
  );
};

export default mint_pending;
