import Head from "next/head";
import Mint from "../components/Mint/Mint";
import styles from "../styles/modules/choose/choose.module.css";
import Header from "../components/Choose/Header";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { ConnectAddress } from "../store/actions/toggle";
import { useWeb3React } from "@web3-react/core";
import { injected } from "../utils/connector";

const mint = () => {
  const { activate, account } = useWeb3React();
  const dispatch = useDispatch();
  const { logout } = useSelector((state) => state.toggle);
  useEffect(() => {
    if (account !== undefined && !logout) {
      dispatch(ConnectAddress(account));
    }
  }, [account, logout]);

  const [loader, setLoader] = useState(false);
  useEffect(() => {
    setTimeout(() => {
      const connectToMetaMask = async () => {
        setLoader(true);
        await activate(injected);
        setLoader(false);
      };
      connectToMetaMask();
    }, 1000);
  }, []);
  return (
    <>
      <Head>
        <title>Mint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.wrapper}>
        <Header mint={true} />
        <Mint loader={loader} />
      </section>
    </>
  );
};

export default mint;
