import Head from "next/head";
import Header from "../components/Choose/Header";
import Name from "../components/Name/Name";
import styles from "../styles/modules/choose/choose.module.css";

const name = () => {
  return (
    <>
      <Head>
        <title>Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.wrapper}>
        <Header name={true} />
        <Name />
      </section>
    </>
  );
};

export default name;
