import Head from "next/head";
import Privacy from "../components/Privacy/Privacy";
// import styles from "../styles/modules/choose/choose.module.css";

const privacy = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Privacy />
    </>
  );
};

export default privacy;
