import Head from "next/head";
import React from "react";
import ReferralError from "../components/ReferralError/ReferralError";

const referralError = () => {
  return (
    <>
      <Head>
        <title>Referral Error</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReferralError />
    </>
  );
};

export default referralError;
