import Head from "next/head";
import React from "react";
import Simplified from "../components/Simplified/Simplified";

const simplified = () => {
  return (
    <>
      <Head>
        <title>Simplified Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Simplified />
    </>
  );
};

export default simplified;
