import Head from "next/head";
import Terms from "../components/Terms/Terms";

const terms = () => {
  return (
    <>
      <Head>
        <title>Terms and Conditions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Terms />
    </>
  );
};

export default terms;
