import Head from "next/head";
import ThankYou from "../components/ThankYou/ThankYou";

const thankyou = () => {
  return (
    <>
      <Head>
        <title>Thank You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThankYou />
    </>
  );
};

export default thankyou;
