import Head from "next/head";
// import Collection from "../components/Collection";
import MargeHomePage from "../../components/MargeHomePage/MargeHomePage";

const index = ({ data }) => {
    return (
        <>
            <Head>
                <title>Homeage</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MargeHomePage data={data} />
            {/* <Collection /> */}
        </>
    );
};

export default index;

export async function getServerSideProps() {
    // Fetch data from external API
    const res = await fetch(`https://metadata.color.museum/api/v1/image/`);
    const data = await res.json();

    // Pass data to the page via props
    return { props: { data } };
}